# Generated by Django 3.1.1 on 2020-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproductinstance',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.RemoveField(
            model_name='orderproductinstance',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='orderproductinstance',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='orderproductinstance',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='orderproductinstance',
            name='refund_requested',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('BD', 'Being Delivered'), ('D', 'Delivered'), ('RR', 'Refund Requested'), ('RG', 'Refund Granted')], default='P', max_length=3),
        ),
        migrations.AddField(
            model_name='orderproductinstance',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('BD', 'Being Delivered'), ('D', 'Delivered'), ('RR', 'Refund Requested'), ('RG', 'Refund Granted')], default='P', max_length=3),
        ),
        migrations.AddField(
            model_name='orderproductinstance',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
